### ISSUE TITLE
This example has problems with my errBot version

### ISSUE THREAD

**Issue by fernand0** [errbotio/err-guess-a-number#1]
Errbot version 6.1.2

There are the following problems:

* .flow file contains the name `Module = guess_flows.py` but it seems that `.py` should not be there.  
* .plug file contains the name `Module = guess.py` but it seems that `.py` should not be there.

When corrected these problems and loading the plugin and so on, with the command `flows list` the bot replies with:
`Computer says nooo. See logs for details:
must be str, not NoneType`

In the logs, we can see:

`n error happened while processing a message (",flows list"): Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/errbot/core.py", line 454, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/errbot/core_plugins/flows.py", line 51, in flows_list
    response.write("- **" + name + "** " + flow_node.description + "\n")
TypeError: must be str, not NoneType
`

**Comment by fernand0** [comment]
The last problem seems to be related to `flow_node.description` which seems not to be initialized. In my case it has a `None` value.

**Comment by fernand0** [comment]
Related: https://github.com/errbotio/errbot/pull/1404#issuecomment-575967919
